[options]

; =========================
; ADDONS
; =========================
addons_path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/design-themes,/mnt/enterprise,/mnt/custom

; =========================
; DATA
; =========================
data_dir = /var/lib/odoo

; =========================
; DATABASE (docker)
; =========================
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = zaccariadb
dbfilter = 

; =========================
; SECURITY
; =========================
admin_passwd = admin
list_db = True

; =========================
; SERVER
; =========================
http_port = 8069
http_enable = True
proxy_mode = False
workers = 0

; =========================
; LOG
; =========================
log_level = debug
log_handler = :INFO
logfile = False

; =========================
; LIMITS (safe dev)
; =========================
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_time_cpu = 600
limit_time_real = 1200
db_maxconn = 64